apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: dns
    namespace: dns
    labels:
      app: dns
      app.kubernetes.io/name: dns
      app.kubernetes.io/component: dns
  spec:
    replicas: 3
    strategy:
      type: Recreate
    selector:
      matchLabels:
        app: dns
    template:
      metadata:
        labels:
          app: dns
          app.kubernetes.io/name: dns
          app.kubernetes.io/component: dns
      spec:
          containers:
          - name: dns
            image: yboaron/kuryr-udp-demo
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
            ports:
            - containerPort: 9090
- apiVersion: v1
  kind: Service
  metadata:
    name: dns
    namespace: dns
    labels:
      app: nginx
      app.kubernetes.io/name: dns
      app.kubernetes.io/component: dns
  spec:
    ports:
      - protocol: UDP
        port: 90
        targetPort: 9090
    selector:
      app.kubernetes.io/name: dns
      app.kubernetes.io/component: dns
    type: NodePort
